language: go
go:
 - 1.5.0
 - 1.5.1
 - 1.5.2
 - 1.5.3
 - 1.5.4
 - 1.6.0
 - 1.6.1
 - 1.6.2
 - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
